config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks
  end

  resources :tasks do
    resources :comments
  end

  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 50 }
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence: true
  validates :content, length: { minimum: 5, maximum: 120 }
  validates :content, uniqueness: true
  has_many :tasks, dependent: :destroy
  belongs_to :user

  def display_created_at
    I18n.l(created_at, format: :default)
  end

  def author_name
    user.display_name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :eyecatch

  validates :content, presence: true
  validates :content, length: { minimum: 5, maximum: 120 }
  validates :content, uniqueness: true
  has_many :comments, dependent: :destroy
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy
  # has_one_attached :avatar

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def prepare_profile
    profile || build_profile
  end

  def display_name
    profile&.nickname || '名無し'
    # nicknameがnilじゃない時にprofileが実行される
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, notice: '保存しました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private

  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @task = Task.find(params[:id])
    @comments = @task.comments.build
  end

  def create
    @task = Task.find(params[:id])
    @comments = @task.comments.build(comment_params)
    if @comments.save
      redirect_to board_task_path(board_id: @task.board_id, id: @task.id), notice: 'コメントを追加'
    else
      flash.now[:error] = '更新できませんでした'
      render :new
    end
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
    # @profile = current_user.profile || current_user.build_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:avatar, :nickname)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit destroy]

  def new
    @board = Board.find(params[:board_id])
    @task = @board.tasks.build
  end

  def create
    @board = Board.find(params[:board_id])
    @task = @board.tasks.build(task_params)
    if @task.save
      redirect_to board_path(@board), notice: 'コメントを追加'
    else
      flash.now[:error] = '更新できませんでした'
      render :new
    end
  end

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @comments = @task.comments
  end

  def edit
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
  end

  def update
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @task.update(task_params)
    redirect_to board_task_path, notice: 'タスクを更新しました'
  end

  private

  def task_params
    params.require(:task).permit(:name, :content, :eyecatch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
.containaer
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
      -# フォームのエラーメッセージ表示
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h1.board_top All Boards
  %div
    - @boards.each do |board|
      = render 'commons/board', board: board

.container
  = link_to new_board_path do
    .add_new
      %h2 + Add new board

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
%h1 Brankets
= link_to board_task_path(board_id: @board.id, task_id: @board.id) do
  - @tasks.each do |task|
    = render 'commons/task', task: task

.container
  = link_to new_board_task_path(@board) do
    .add_new
      %h2 + Add new card

app/views/comments/_form.html.haml
.containaer
  %ul
    - comment.errors.full_messages.each do |message|
      %li= message
      -# フォームのエラーメッセージ表示
  = form_with(model: @comment, url: task_comments_path(@task), method: 'post', local: true) do |f|
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/comments/new.html.haml
= render 'form', comment: @comment

app/views/commons/_board.html.haml
= link_to board_path(board) do
  .card
    .card_detail
      .card_detail_title
        %p= board.title
        .card_detail_content
          %p= board.content
          = image_tag board.user.avatar_image

      - if user_signed_in? && current_user.has_written?(board)
        .card_detail_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to '編集する', edit_board_path(board)
              = link_to '削除する', board_path(board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか' }

app/views/commons/_comment.html.haml
= link_to task_comment_path(@comments) do
  .container
    .task_image
      = image_tag @board.user.avatar_image
    .task_content
      = comment.content
    .task_detail
      - if user_signed_in? && current_user.has_written?(@board)
        .task_detail_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to '編集する', edit_task_comment_path(board_id: @board.id, task_id: @task.id, id: comment.id)
              = link_to '削除する', task_comment_path(board_id: @board.id, task_id: @task.id, id: comment.id) , data: { method: 'delete', confirm: '本当に削除してもよろしいですか' }

app/views/commons/_task.html.haml
= link_to board_task_path(board_id: @board.id, id: task.id) do
  .board
    .board_detail_name
      %p= task.name
    - if task.eyecatch.attached?
      .eyecatch
        = image_tag task.eyecatch
      .board_detail_content
        %p= task.content
    - if user_signed_in? && current_user.has_written?(@board)
      .board_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_task_path(board_id: @board.id, id: task.id)
            = link_to '削除する', task_path(board_id: @board.id, id: task.id), data: { method: 'delete', confirm: '本当に削除してもよろしいですか' }

app/views/layouts/application.html.haml
!!!
%html
  %body
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %header.header
      .header_logos
        %p.header_pageTitle
          = link_to 'TodoApp', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          -# = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: {method: 'delete'}
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
  - if flash.present?
    .flash
      - flash.each do |key, value|
        %div{:class => key}= value
  .header_title_line
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, 'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'
    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profile_image
    = image_tag current_user.avatar_image

    .profile_name
      = current_user.display_name
    .profile_edit
      = link_to 'Edit', edit_profile_path

app/views/tasks/_form.html.haml
.cantainer
  %url
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: board_tasks_path, local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/tasks/new.html.haml
= render 'form', task: @task

app/views/tasks/show.html.haml
-# %h1 Brankets
-# = link_to board_path(@board) do
-#   - @tasks.each do |task|
-#     = render 'commons/task', task: task
.container
  .task_name
    = @task.name
  - if @task.eyecatch.attached?
    .eyecatch
      = image_tag @task.eyecatch
  .task_content
    = @task.content

.container
  %h1 Comment
  - @comments.each do |comment|
    = render 'commons/comment', comment: comment

.container
  = link_to new_task_comment_path(@comments) do
    .add_new
      %h2 + Add new comment